AWS_ACCESS_KEY_ID = "AWSACCESSKEYID"
AWS_SECRET_ACCESS_KEY = "aWsSeCrEtAcCeSsKeY"
AWS_REGION = "ap-northeast-2"
EC2_INSTANCE_IDS = ["i-0a1b2c3d4e5f6g7h8"]
TIME_SETTING = {
    "STARTUP_TIME": "16:55",
    "SHUTDOWN_TIME": "00:10",
}
